source/api/urls.py
from django.urls import path

from api.views import favorite_post, favorite_delete_post

urlpatterns = [
    path('photos/<int:pk>/favorite_post/', favorite_post, name='favorite_post'),
    path('photos/<int:pk>/favorite_delete_post/', favorite_delete_post, name='favorite_delete_post'),
]

source/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.photos import IndexView, PhotoCreateView, PhotoUpdateView, PhotoDetailView, PhotoDeleteView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('photos/', IndexView.as_view(), name='photo_list'),
    path('photos/create', PhotoCreateView.as_view(), name='photo_create'),
    path('photos/<int:pk>/detail', PhotoDetailView.as_view(), name='photo_detail'),
    path('photos/<int:pk>/update', PhotoUpdateView.as_view(), name='photo_update'),
    path('photos/<int:pk>/delete', PhotoDeleteView.as_view(), name='photo_delete'),
]

source/webapp/models/photo.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models


class Photo(models.Model):
    image = models.ImageField(
        null=False,
        blank=False,
        upload_to='photos',
        verbose_name='Фотография',
    )
    caption = models.CharField(
        max_length=256,
        null=False,
        blank=False,
        verbose_name='Подпись',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Время создания",
    )
    author = models.ForeignKey(
        to=User,
        related_name='photos',
        verbose_name='Фотографии',
        null=False,
        on_delete=models.CASCADE,
    )
    user_favorites = models.ManyToManyField(
        verbose_name='Избранные фотографии',
        to=get_user_model(),
        related_name='user_favorites'
    )

    def __str__(self):
        return f'{self.author.username} - {self.caption}'

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

source/webapp/forms.py
from django import forms

from webapp.models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'caption')

source/webapp/views/photos.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from webapp.forms import PhotoForm
from webapp.models import Photo


class IndexView(ListView):
    template_name = 'photo_list.html'
    model = Photo
    context_object_name = 'photos'
    ordering = ('-created_at',)


class PhotoCreateView(LoginRequiredMixin, CreateView):
    template_name = 'photo_create.html'
    model = Photo
    form_class = PhotoForm
    permission_denied_message = 'У вас нет прав доступа'

    def form_valid(self, form):
        photo = form.save(commit=False)
        photo.author = self.request.user
        photo.save()
        return redirect('index')


class PhotoUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'photo_update.html'
    model = Photo
    form_class = PhotoForm
    permission_denied_message = 'У вас нет прав доступа'

    def test_func(self):
        photo = get_object_or_404(Photo, pk=self.kwargs.get('pk'))
        return self.request.user.has_perm('webapp.change_photo') or (self.request.user.id == photo.author.id)

    def get_success_url(self):
        return reverse('index')


# , kwargs={'pk': self.object.pk}


class PhotoDetailView(DetailView):
    template_name = 'photo_detail.html'
    model = Photo




class PhotoDeleteView(UserPassesTestMixin, DeleteView):
    model = Photo
    permission_denied_message = 'У вас нет прав доступа'

    def test_func(self):
        photo = get_object_or_404(Photo, pk=self.kwargs.get('pk'))
        return self.request.user.has_perm('webapp.change_photo') or (self.request.user.id == photo.author.id)

    def get_success_url(self):
        return reverse('index')

source/webapp/templates/photo_create.html
{% extends 'base.html' %}

{% block title %}Создание фото{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row d-flex justify-content-center">
            <div class="col-5 card text-bg-light form-margins">
                <h3>Создание фотографии</h3>
                {% include 'partial/post_create_update_form.html' with button_text='Создать' %}
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/photo_detail.html
{% extends 'base.html' %}

{% block title %}Детальный просмотр фотографии{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row d-flex justify-content-center">
            <div class="card col-7 text-bg-light form-margins card-paddings card-back ">
                <img src="{{ photo.image.url }}" class="card-img-top" alt="{{ photo.caption }}">
                <div class="card-body">
                    <h5 class="card-title">{{ photo.author.username }}</h5>
                    <p class="card-text">{{ photo.caption }}</p>
                    <p class="card-text"><small class="text-body-secondary">{{ photo.created_at }}</small></p>
                </div>
                {% if user.is_authenticated %}
                    <div class="row">
                        {% if perms.webapp.change_photo or user.id == photo.author.id %}
                            <div class="col-3">
                                <a class="btn btn-primary green edit-detail-button"
                                   href="{% url 'photo_update' photo.pk %}">
                                    Редактировать
                                </a>
                            </div>
                        {% endif %}
                        {% if perms.webapp.delete_photo or user.id == photo.author.id %}
                            <div class="col-3">
                                <form action="{% url 'photo_delete' photo.pk %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class='btn btn-danger'>Удалить</button>
                                </form>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/photo_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Главная{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row">
            <div class="col">
                <h1 class="project-task-name-left">
                    Последние фотографии
                </h1>
            </div>
        </div>
        <div class="row">
            {% if photos %}
                {% for photo in photos %}
                    <div class="col-4">
                        <div class="card card-back" style="width: 18rem;">
                            <img src="{{ photo.image.url }}" class="card-img-top" alt="{{ photo.caption }}">
                            <div class="card-body">
                                <h4 class="card-title">{{ photo.author.username }}</h4>
                                <p class="card-text">{{ photo.caption }}</p>
                                <p class="card-text">{{ photo.created_at }}</p>
                            </div>
                            <div class="row">
                                <div class="col-5">
                                    <a href="{% url 'photo_detail' photo.pk %}"
                                       class="btn btn-primary green button-detail-margins">Подробнее</a>
                                </div>
                                <div class="col-2">
                                    {% if user.is_authenticated %}
                                        {% if photo in user.user_favorites.all  %}
                                            <button id="favorite_post" class="button-favorite-post"
                                                    value="{{ photo.id }}"
                                                    data-photo-status="false">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35"
                                                     fill="currentColor" class="bi bi-star svg-color" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                                </svg>
                                            </button>
                                        {% else %}
                                            <button id="favorite_post" class="button-favorite-post"
                                                    value="{{ photo.id }}"
                                                    data-photo-status="true">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35"
                                                     fill="currentColor" class="bi bi-star-fill svg-color"
                                                     viewBox="0 0 16 16">
                                                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                                </svg>
                                            </button>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-6">
                    <h5>По вашему запросы задачи не найдены</h5>
                </div>
            {% endif %}
        </div>
    </div>

    <script src="{% static 'js/to_favorite_script.js' %}"></script>
{% endblock %}

source/webapp/templates/photo_update.html
{% extends 'base.html' %}

{% block title %}Редактирование фото{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row d-flex justify-content-center">
            <div class="col-5 card text-bg-light form-margins">
                <h3>Редактирование фотографии</h3>
                {% include 'partial/post_create_update_form.html' with button_text='Редактировать' %}
            </div>
        </div>
    </div>
{% endblock %}